# Generated by Django 2.2.17 on 2021-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
