# Generated by Django 2.2.17 on 2021-03-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_business_owner_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='price_currency',
        ),
    ]
