# Generated by Django 2.2.17 on 2021-01-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business_Owner'),
        ),
        migrations.CreateModel(
            name='Bookings_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Bookings')),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business_Owner')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Customer')),
            ],
        ),
    ]
