# Generated by Django 2.2.17 on 2021-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210321_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='category',
            field=models.CharField(choices=[('Gym Booking', 'Gym Booking'), ('Personal Trainer', 'Personal Trainer'), ('Pilates', 'Pilates'), ('Yoga', 'Yoga'), ('Crossfit', 'Crossfit')], max_length=200, null=True),
        ),
    ]
