# Generated by Django 2.2.17 on 2021-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_business_owner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
