# Generated by Django 2.2.17 on 2021-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210128_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
