# Generated by Django 2.2.17 on 2021-04-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210417_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
