# Generated by Django 2.2.17 on 2021-01-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210128_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_location',
            name='business_name',
        ),
    ]
