# Generated by Django 2.2.17 on 2021-04-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210417_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RenameField(
            model_name='business_owner',
            old_name='name',
            new_name='Owners_name',
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business'),
        ),
        migrations.AlterField(
            model_name='customer_bookings',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Customer'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business'),
        ),
    ]
