# Generated by Django 2.2.17 on 2021-01-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_booking_location_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='business_name',
        ),
        migrations.AddField(
            model_name='business_owner',
            name='available_bookings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Bookings'),
        ),
    ]
