# Generated by Django 2.2.17 on 2021-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210417_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_owner',
            old_name='Owners_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='business_owner',
            name='business_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
