# Generated by Django 2.2.17 on 2021-01-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210129_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_owner',
            name='available_bookings',
        ),
        migrations.AddField(
            model_name='business_owner',
            name='available_bookings',
            field=models.ManyToManyField(to='pages.Bookings'),
        ),
    ]
