# Generated by Django 2.2.17 on 2021-04-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210417_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='Business',
        ),
    ]
