# Generated by Django 2.2.17 on 2021-04-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_bookings_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_owner',
            old_name='name',
            new_name='Owners_name',
        ),
    ]
