# Generated by Django 2.2.17 on 2021-01-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210129_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='location',
        ),
    ]
