# Generated by Django 2.2.17 on 2021-02-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_bookings_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings_Order',
            new_name='Customer_Bookings',
        ),
    ]
