# Generated by Django 2.2.17 on 2021-02-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210207_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='description',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='name',
        ),
    ]
