# Generated by Django 2.2.17 on 2021-04-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210418_0038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buisness',
            new_name='Business',
        ),
        migrations.AddField(
            model_name='bookings',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business'),
        ),
    ]
