# Generated by Django 2.2.17 on 2021-04-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210418_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_owner',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Business'),
        ),
    ]
