# Generated by Django 2.2.17 on 2021-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210209_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='available_bookings',
            field=models.ManyToManyField(to='pages.Bookings'),
        ),
        migrations.DeleteModel(
            name='Available_Bookings',
        ),
    ]
