# Generated by Django 2.2.17 on 2021-04-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_bookings',
            name='business_name',
        ),
        migrations.AddField(
            model_name='customer_bookings',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Order'),
        ),
    ]
