# Generated by Django 2.2.17 on 2021-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20210418_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Bookings',
            new_name='CustomerBookings',
        ),
    ]
