# Generated by Django 2.2.17 on 2021-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20210418_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
