# Generated by Django 2.2.17 on 2021-04-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20210418_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='booking',
        ),
    ]
