# Generated by Django 2.2.7 on 2021-04-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_customerbooking_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='order_status',
        ),
    ]
