# Generated by Django 2.2.7 on 2021-04-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_customerbooking_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='user',
        ),
    ]
