# Generated by Django 2.2.7 on 2021-04-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20210426_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
