# Generated by Django 2.2.7 on 2021-04-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_customer_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
    ]
