# Generated by Django 2.2.7 on 2021-04-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20210426_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
