# Generated by Django 2.2.7 on 2021-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20210426_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
