# Generated by Django 2.2.7 on 2021-04-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_bookingitem_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='complete',
        ),
    ]
