# Generated by Django 2.2.7 on 2021-04-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_remove_bookingitem_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='customer_booking',
            new_name='customerbooking',
        ),
    ]
