# Generated by Django 2.2.7 on 2021-04-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20210428_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_owner',
            name='name',
        ),
        migrations.AddField(
            model_name='business_owner',
            name='business_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Customer'),
        ),
    ]
