# Generated by Django 2.2.7 on 2021-05-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20210428_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_owner',
            name='Descprtion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
