# Generated by Django 2.2.7 on 2021-05-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_business_owner_descprtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_owner',
            old_name='Descprtion',
            new_name='descprtion',
        ),
    ]
