# Generated by Django 2.2.7 on 2021-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20210503_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_owner',
            old_name='descprtion',
            new_name='description',
        ),
    ]
